# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_teammembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleader',
            name='Leader',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
        migrations.DeleteModel(
            name='TeamMembers',
        ),
    ]
