# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_team_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='TeamLeader',
            new_name='TeamLeaders',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamMembers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
