# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20160706_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='TeamLeaders',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamLeaders',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamMembers',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamMembers',
            field=models.ManyToManyField(related_name='TeamMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
