# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20160706_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamLeaders',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamMembers',
        ),
        migrations.AddField(
            model_name='teammember',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='TeamMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='TeamMemberRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TeamMemberRole'),
        ),
    ]
