# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='Office',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Section',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='SiteUser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='section',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skill',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
